# Generated by Django 3.2 on 2021-05-03 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('description', models.TextField(null=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='диагональ')),
                ('display_type', models.CharField(max_length=255, verbose_name='тип дисплея')),
                ('resolution', models.CharField(max_length=255, verbose_name='разрещение экрана')),
                ('accum_value', models.CharField(max_length=255, verbose_name='обьем батареи')),
                ('ram', models.CharField(max_length=255, verbose_name='оперативная память')),
                ('sd_card', models.BooleanField(default=True)),
                ('sd', models.CharField(max_length=255, verbose_name='максимальный обьём встраиваемой памяти')),
                ('main_cam', models.CharField(max_length=255, verbose_name='главная камера')),
                ('frontal_cam', models.CharField(max_length=255, verbose_name='фронтальная камера')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='категория')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='наименование')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('description', models.TextField(null=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='цена')),
                ('diagonal', models.CharField(max_length=255, verbose_name='диагональ')),
                ('display_type', models.CharField(max_length=255, verbose_name='тип дисплея')),
                ('processor_freq', models.CharField(max_length=255, verbose_name='частота процессора')),
                ('ram', models.CharField(max_length=255, verbose_name='оперативная память')),
                ('video', models.CharField(max_length=255, verbose_name='видеокарта')),
                ('time_without_charge', models.CharField(max_length=255, verbose_name='время работы аккамулятора')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='категория')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
